# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - argoxpaasnginxwarp

on:
  push:
    branches:
      - endwarp
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_21c32e3cdb0f4f55a1445c3826a4532a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_51ec9a1f486b4c70a275776214f7e294 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_21c32e3cdb0f4f55a1445c3826a4532a }}/argoxendwarp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'argoxpaasnginxwarp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_28695c779b0e411d953a8171f6978fc1 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_21c32e3cdb0f4f55a1445c3826a4532a }}/argoxendwarp:${{ github.sha }}'