# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testargo-nginx-xray-paas

on:
  push:
    branches:
      - nowarp
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0cedb842942046e5985f289b7ba2eb4b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_62bf7b9b66c9490db831b321de67243a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0cedb842942046e5985f289b7ba2eb4b }}/argoxpaasnowarp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testargo-nginx-xray-paas'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_51b16484de334e22916b11f2b08bf9b0 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0cedb842942046e5985f289b7ba2eb4b }}/argoxpaasnowarp:${{ github.sha }}'